name: "Prepare Composer"
description: ""
inputs:
  path:
    description: "Where dependencies should be copied to"
    required: true
  from:
    description: "Take installed dependencies from this previous build"
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Path Setup
      shell: bash
      env:
        PATH_DIR: ${{ inputs.path }}
        FROM_DIR: ${{ inputs.from }}
      run: "${{ github.action_path }}/prepare-composer-wp.sh"

    - name: Prepare WP Core update handler
      shell: bash
      env:
        PATH_DIR: ${{ inputs.path }}
        FROM_DIR: ${{ inputs.from }}
      run: "${{ github.action_path }}/prepare-wp-core-update.sh"
