name: "Prepare Composer"
description: ""
inputs:
  source:
    description: "Source folder"
    required: false
    default: 'source'
  target:
    description: "Target folder"
    required: false
    default: 'target'
    
runs:
  using: "composite"
  steps:
    - name: Path Setup
      shell: bash
      env:
        SOURCE_DIR: ${{ inputs.source }}
        TARGET_DIR: ${{ inputs.target }}
      run: "${{ github.action_path }}/prepare-composer-wp.sh"
